AllCops:
  Exclude:
    - app/views/**/*
    - app/helpers/ApplicationHelper
    - bin/*
    - config/initializers/*
    - db/schema.rb
    - db/migrate/**/*devise*.rb
    - spec/spec_helper.rb
    - Guardfile

Metrics/LineLength:
  Description: 'Limit lines to 180 characters.'
  Max: 180

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
