source "https://rubygems.org"

# Living life on the edge with the most recent version of ruby
ruby "2.1.3"

# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", "4.1.5"
# Use PostgreSQL as the database for Active Record
gem "pg"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.0"
# Use jquery as the JavaScript library
gem "jquery-rails"
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem "turbolinks"

# bundle exec rake doc:rails generates the API under doc/api.
gem "sdoc", "~> 0.4.0",          group: :doc

# Use textacular for fuzzy string searching
gem "textacular", :git => "https://github.com/textacular/textacular.git"

# Use figaro for setting environment variables
gem "figaro"

#Salesforce gems
gem "databasedotcom"
gem "databasedotcom-rails"

#Recommended gems
group :development do
    gem "better_errors"
    gem "binding_of_caller"
    gem "bullet"
    gem "annotate", "~> 2.6.5"
    gem "spring"
end
