source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails"
# Use PostgreSQL as the database for Active Record
gem "pg"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.0"

# bundle exec rake doc:rails generates the API under doc/api.
gem "sdoc", "~> 0.4.0",          group: :doc

# Use textacular for fuzzy string searching
gem "textacular", :git => "https://github.com/textacular/textacular.git"

# Use figaro for setting environment variables
gem "figaro"

# For hashing and storing secure passwords
gem "bcrypt"

# Salesforce gems
gem "databasedotcom"
gem "databasedotcom-rails"

gem "rails_12factor", group: :production

gem 'salesforce_bulk'
gem 'salesforce_bulk_api'

gem 'newrelic_rpm'

#Recommended gems
group :development do
    gem "better_errors"
    gem "binding_of_caller"
    gem "bullet"
    gem "annotate", "~> 2.6.5"
    gem "spring"
    gem "byebug"
end
