# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
include Databasedotcom::Rails::Controller

task :load_sf => :environment do
  if not LastModified.any?
    LastModified.create(last_modified_datetime: Time.now)
    accounts = Account.query("LastModifiedDate > " + @last.last_modified_datetime.to_s + "")

  else
    last = LastModified.first
    #Account.query("LastModifiedDate > " + @last.last_modified_datetime.to_s + "")
    accounts = Account.all #Temporary
    last.update_attributes(last_modified_datetime: Time.now)
  end
  accounts.each do |a|
    pa = PersonAccount.find_or_initialize_by(sf_id: a.Id)
    pa.update(first_name: a.FirstName, last_name: a.LastName, birthday: a.PersonBirthdate)
    pa.save
  end
end
